
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Printer, Download, Plane, Hotel } from "lucide-react";
import { Separator } from "@/components/ui/separator";

const RawItineraryView = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [rawContent, setRawContent] = useState<string>("");

  useEffect(() => {
    if (location.state?.rawResponse) {
      setRawContent(location.state.rawResponse);
    } else {
      // If no raw response is available, redirect to the itineraries page
      navigate("/itineraries");
    }
  }, [location.state, navigate]);

  const handlePrint = () => {
    window.print();
  };

  // Function to find a destination from the content for navigation purposes
  const extractDestination = (): string => {
    // Simple regex to try to find a destination in the content
    // This is a basic implementation and might need refinement
    const destinationMatch = rawContent.match(/destination:?\s*([A-Za-z\s,]+)[\n<]/i);
    return destinationMatch ? destinationMatch[1].trim() : "";
  };

  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      <Navbar />
      <main className="flex-grow container mx-auto px-4 py-8">
        <div className="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between">
          <div>
            <Button 
              variant="outline" 
              className="mb-4" 
              onClick={() => navigate(-1)}
            >
              <ArrowLeft className="h-4 w-4 mr-2" /> Back
            </Button>
            <h1 className="text-2xl font-bold text-gray-800">Your Travel Itinerary</h1>
            <p className="text-gray-600 mb-4">
              Personalized travel plan generated by our AI travel assistant
            </p>
          </div>
          <div className="flex gap-2 mt-2 sm:mt-0">
            <Button 
              variant="outline" 
              className="flex items-center gap-2"
              onClick={handlePrint}
            >
              <Printer className="h-4 w-4" /> Print
            </Button>
            <Button className="flex items-center gap-2">
              <Download className="h-4 w-4" /> Save
            </Button>
          </div>
        </div>
        
        <Separator className="my-6" />

        {/* Enhanced styling for the itinerary content */}
        <div className="bg-white rounded-xl shadow-md overflow-hidden print:shadow-none">
          <div className="p-6 sm:p-8 max-w-4xl mx-auto">
            {/* Apply enhanced styling while preserving the original HTML */}
            <div 
              className="itinerary-content prose prose-slate max-w-none"
              dangerouslySetInnerHTML={{ __html: rawContent }}
            />

            {/* Navigation buttons for flights and hotels */}
            <div className="mt-8 flex flex-col sm:flex-row gap-4 print:hidden">
              <Button 
                className="bg-ocean-600 hover:bg-ocean-700 flex items-center gap-2"
                onClick={() => navigate('/flights', { state: { destination: extractDestination() } })}
              >
                <Plane className="h-4 w-4" /> Find Flights
              </Button>
              <Button 
                className="bg-teal-600 hover:bg-teal-700 flex items-center gap-2"
                onClick={() => navigate('/hotels', { state: { destination: extractDestination() } })}
              >
                <Hotel className="h-4 w-4" /> Browse Hotels
              </Button>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default RawItineraryView;
